# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ede5dc54f81a469d76b33eec4c15c45681f41657e9b71c66e35f6ee3e6297044b42411c5d67ded44929bcd6dd37b0110f0b4ad7a94ccf719388a3d8b28c198d

test:
  secret_key_base: b7e23196e41613061068df2ac12c75dd3fb4a10cf50b5212ceefe952cc0eae0b8a5cf9333b0e67fe417466bd22ebfde8edd28597d6acbf5f32ccc8782e7ddaef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
